'''
Contains the constants used in the frontend.py app
'''

# FONTS

FONT_NAME = 'Helvetica'

# COLORS

BG_COLOR = '#19233c'
QUESTION_BG_COLOR = '#121a2c'
BUTTON_BG_COLOR = '#19233c'
BUTTON_BORDER_COLOR_UNANSWERED = '#00E4FF'
BUTTON_BORDER_COLOR_CORRECT = '#3EFF00'
BUTTON_BORDER_COLOR_WRONG = '#FF2700'
TEXT_COLOR = '#FFFFFF'